In [2]:
# load tidy dataset

import pandas as pd
import os.path
import numpy as np
from itertools import combinations
import glob

#import numpy as np
#import loadTidyCSV.py

def loadTidy(tidyData): 
    assert os.path.isfile(tidyData), "desired file does not exist" 
    df = pd.read_csv(tidyData, header = None, names = ["date", "animal", "session", "trial", "stimulus", "neuronID", "timePt", "CaSignal"])
    return df 

# tidy csv file and dir (use makeTidy_Anderson.m to convert Ann's structure to csv)
tidyDataDir = '/home/orthogonull/a_MHR/a_research/a_gitResearch/git_ignored/imagingAnalysis/data/2_tidyFormat/'
tidyDataFileTemplate = 'mouse'
tidyDataFileExt = '.csv'

# get all input files you want to add to the same dataset
dataFiles = np.sort(glob.glob(\
    "/home/orthogonull/a_MHR/a_research/a_gitResearch/git_ignored/imagingAnalysis/data/2_tidyFormat/mouse*.csv"))
print("data files: \n", dataFiles)


print("\n loading and appending to prior pandas data frame")
dataLst = []
for file in dataFiles:
    print(file)
    dataLst.append(loadTidy(file))
df = pd.concat(dataLst)

print('finished loading')

############# ALL DATA STORED HERE IN DF
    

data files: 
 [ '/home/orthogonull/a_MHR/a_research/a_gitResearch/git_ignored/imagingAnalysis/data/2_tidyFormat/mouse1.csv'
 '/home/orthogonull/a_MHR/a_research/a_gitResearch/git_ignored/imagingAnalysis/data/2_tidyFormat/mouse2.csv'
 '/home/orthogonull/a_MHR/a_research/a_gitResearch/git_ignored/imagingAnalysis/data/2_tidyFormat/mouse3.csv'
 '/home/orthogonull/a_MHR/a_research/a_gitResearch/git_ignored/imagingAnalysis/data/2_tidyFormat/mouse4.csv'
 '/home/orthogonull/a_MHR/a_research/a_gitResearch/git_ignored/imagingAnalysis/data/2_tidyFormat/mouse5.csv']

 loading and appending to prior pandas data frame
/home/orthogonull/a_MHR/a_research/a_gitResearch/git_ignored/imagingAnalysis/data/2_tidyFormat/mouse1.csv
/home/orthogonull/a_MHR/a_research/a_gitResearch/git_ignored/imagingAnalysis/data/2_tidyFormat/mouse2.csv
/home/orthogonull/a_MHR/a_research/a_gitResearch/git_ignored/imagingAnalysis/data/2_tidyFormat/mouse3.csv
/home/orthogonull/a_MHR/a_research/a_gitResearch/git_ignored/imagingAn

In [3]:
## survey/search data to prepare for split operation
metaStrs = [['dates','date'],['animals','animal'],['sessions','session'],['maxTrials','trial'],['stimuli','stimulus']]

## this dictionary holds useful info regarding the range of inputs to loop/search over subsequently
metaDct = {}
for a,b in metaStrs:
    print(a,b)
    metaDct[a] = np.unique(df[b].tolist())
print(metaDct)


dates date
animals animal
sessions session
maxTrials trial
stimuli stimulus
{'dates': array(['2017_05_00'], 
      dtype='<U10'), 'animals': array([1, 3, 4, 5, 7]), 'sessions': array([1, 2, 3]), 'maxTrials': array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21]), 'stimuli': array(['USS', 'baseline', 'female', 'male', 'mineral oil odor',
       'peanut odor', 'pred odor', 'rat', 'tone', 'toy'], 
      dtype='<U16')}


In [24]:
######### PARAMETERS #########
threshTPs_stdFromMean = 1



In [26]:
### get all pairs of stimuli
stimCmbTpl = tuple(combinations(metaDct['stimuli'],2)) 

######### MAIN LOOP ##########
totalNumComparisons = 0;
for (stimA, stimB) in stimCmbTpl:
    
    ## get all data for both trial types
    indsBoth = (df['stimulus']==stimA) | (df['stimulus']==stimB)
    df_bothStimuli = df[indsBoth]

    
    #### select data by animals and sessions
    for animal in metaDct['animals']:
        print('animal: ', animal)
        for session in metaDct['sessions']:
            print('session:', session)
            inds_animalSession = (df_bothStimuli['animal'] == animal) & (df_bothStimuli['session'] == session)
            df_animalSession = df_bothStimuli[inds_animalSession]
            
            ## get both stim
            df_anmlSessStimA = df_animalSession[df_animalSession['stimulus'] == stimA]
            df_anmlSessStimB = df_animalSession[df_animalSession['stimulus'] == stimB]
            print(stimA,stimB)
            
            ## get lists of trial numbers of each stimuli's presentations 
            trials_stimA = np.unique(df_anmlSessStimA['trial'].tolist())
            trials_stimB = np.unique(df_anmlSessStimB['trial'].tolist())
            print(trials_stimA,trials_stimB)
        
            #### get number of timePts in each trial selected above 
            ## (1 to 3 presentations of the same stimuli exist per session in Prabhat's data)
            numTimePtsPerTrial = np.empty((2,max(len(trials_stimA),len(trials_stimA))))
            numTimePtsPerTrial[:] = np.nan
            stimInd = 0;
            for thisStimTypeTrialNums in [trials_stimA, trials_stimB]:
                trialInd = 0
                for trial in thisStimTypeTrialNums:
                    inds_thisTrial = (df_animalSession['trial']==trial)
                    numTimePtsPerTrial[stimInd,trialInd] = np.sum(inds_thisTrial)
                    trialInd += 1
                stimInd += 1
            print(numTimePtsPerTrial) # rows are for stimuli type; cols are presentation of that stimulus            
            
            #### test and sort candidate comparisons based on whether the number of trials per session 
            ##      and approximate number of timePts match
            
            ## no trials of either type --> discard this comparison for this animal/session   
            if np.all(np.isnan(numTimePtsPerTrial)):
                print("discarded: neither stimulus type were found for this animal and session")
                break # skip to next session (WORK: handle this)
                
            ## different numbers of trials per stimuli/session --> discard this comparison for this animal/session 
            elif np.any(np.isnan(numTimePtsPerTrial)): 
                print("discarded: mismatching numbers of trials per stimulus type for this animal/session")
                break # skip to next session (WORK: handle this)
            
            ## FULFILLED here: condition that allows analysis to proceed to attempted data
            elif not np.any(np.isnan(numTimePtsPerTrial)): 
                print("trial numbers match")
            else:
                raise RuntimeError('unexpected trial comparison occurred')
            
            print("checking approx num of time points")
            
            #### discard this comparison for this animal/session if number of time points are too dissimilar
            minTPs = np.min(numTimePtsPerTrial) 
            maxTPs = np.max(numTimePtsPerTrial)
            meanTPs = np.mean(numTimePtsPerTrial)
            stdTPs = np.std(numTimePtsPerTrial)
            print('min', minTPs)
            print('max', maxTPs)
            print('std', stdTPs)
            print('mean',meanTPs)
            if (np.abs(minTPs-meanTPs) > (threshTPs_stdFromMean * np.abs(meanTPs-stdTPs))) \
                or (np.abs(maxTPs-meanTPs) > (threshTPs_stdFromMean * np.abs(meanTPs-stdTPs))): 
                print("discarded this comparison because variance in trial length is above the user's threshold")
                break # skip to next session (WORK: handle this)
            totalNumComparisons += 1    
            print('\n')
        print('########\n')

print('total number of comparisons: ', totalNumComparisons)

           

animal:  1
session: 1
USS baseline
[ 5 10 16] [ 1  8 15]
[[ 26808.  26784.  26808.]
 [  8880.   8712.  35424.]]
trial numbers match
checking approx num of time points
min 8712.0
max 35424.0
std 9980.77592174
mean 22236.0
discarded this comparison because variance in trial length is above the user's threshold
########

animal:  3
session: 1
USS baseline
[ 4 11 17] [ 1  8 15]
[[ 38010.  33810.  33690.]
 [ 20220.  20460.  20340.]]
trial numbers match
checking approx num of time points
min 20220.0
max 38010.0
std 7550.14072717
mean 27755.0


session: 2
USS baseline
[ 6 12 16] [ 1  8 15]
[[ 32130.  31290.  37380.]
 [ 23835.  25620.  23870.]]
trial numbers match
checking approx num of time points
min 23835.0
max 37380.0
std 4994.68585654
mean 29020.8333333


session: 3
USS baseline
[ 3 14 17] [ 1  8 15]
[[ 34646.  36958.  39304.]
 [ 23018.  23086.  23596.]]
trial numbers match
checking approx num of time points
min 23018.0
max 39304.0
std 7000.77164001
mean 30101.3333333


########

animal: 

[ 1 12] [ 2 14]
[[ 54810.  56862.]
 [ 54540.  54810.]]
trial numbers match
checking approx num of time points
min 54540.0
max 56862.0
std 934.040015203
mean 55255.5


########

animal:  1
session: 1
USS peanut odor
[ 5 10 16] []
[[ 26808.  26784.  26808.]
 [    nan     nan     nan]]
discarded: mismatching numbers of trials per stimulus type for this animal/session
########

animal:  3
session: 1
USS peanut odor
[ 4 11 17] []
[[ 38010.  33810.  33690.]
 [    nan     nan     nan]]
discarded: mismatching numbers of trials per stimulus type for this animal/session
########

animal:  4
session: 1
USS peanut odor
[ 4 11] [7 9]
[[ 63672.  62328.]
 [ 65576.  64512.]]
trial numbers match
checking approx num of time points
min 62328.0
max 65576.0
std 1188.18685399
mean 64022.0


session: 2
USS peanut odor
[5 9] [ 4 16]
[[ 55517.  55076.]
 [ 66101.  59437.]]
trial numbers match
checking approx num of time points
min 55076.0
max 66101.0
std 4419.84006357
mean 59032.75


session: 3
USS peanut odor


IndexError: index 1 is out of bounds for axis 1 with size 1

In [19]:
testInds = (df['animal']==1) & (df['session']==1) & (df['stimulus']=='USS') & (df['trial']==5)
print(np.sum(testInds))

26808


In [49]:
     
                
                
                try:                    
                    assert trialA != [] and trialB != [], "no fair comparison available (trial not conducted for one of the stimulus types)"
#                     print("fair comparisons exist --> proceeding")
                except:
                    print("expection")
                    print(trialA)
                    print(trialB)
                    numTimePts_thisTrial_stimA = np.unique(df_anmlSessStimA[df_anmlSessStimA['trial'] == str(trialA)]).tolist()
                    numTimePts_thisTrial_stimB = np.unique(df_anmlSessStimB[df_anmlSessStimA['trial'] == str(trialB)]).tolist()
                    print(numTimePts_thisTrial_stimA,numTimePts_thisTrial_stimB)
                    break    
            
            indsB = (df_bothStimuli['stimulus'] == stimB) & (df_bothStimuli['session'] == session)
            numA = np.sum(indsA)
            numB = np.sum(indsB)
            print(numA,numB)
    #         print(df_bothStimuli[indsA],df_bothStimuli[indsB])
            print("sum",np.sum(indsA))
        print('\n')

    ## (REALLY? SAME RANDOMIZATION FOR EVERY ANIMAL?)

animal:  1
session: 1
USS baseline
[ 5 10 16] [ 1  8 15]
expection
5
1


/home/orthogonull/anaconda3/envs/py36/lib/python3.6/site-packages/pandas/core/ops.py:798: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  result = getattr(x, name)(y)


TypeError: invalid type comparison

In [ ]:
np.unique(df_anmlSessStimA[df_anmlSessStimA['trial'] == trialA].tolist())

In [88]:
print(metaDct['animals'])
print(metaDct['stimuli'])



[1]
['USS' 'baseline' 'female' 'male' 'rat' 'tone' 'toy']


In [91]:
# this works but is against the whole point of doing pandas in the first place

for date in metaDct['dates']:
    for animal in metaDct['animals']:
        for session in metaDct['sessions']:
            for stimulus in metaDct['stimuli']:
                print(date, animal, session, stimulus)
                
    

2017_05_00 1 1 USS
2017_05_00 1 1 baseline
2017_05_00 1 1 female
2017_05_00 1 1 male
2017_05_00 1 1 rat
2017_05_00 1 1 tone
2017_05_00 1 1 toy
2017_05_00 1 2 USS
2017_05_00 1 2 baseline
2017_05_00 1 2 female
2017_05_00 1 2 male
2017_05_00 1 2 rat
2017_05_00 1 2 tone
2017_05_00 1 2 toy
2017_05_00 1 3 USS
2017_05_00 1 3 baseline
2017_05_00 1 3 female
2017_05_00 1 3 male
2017_05_00 1 3 rat
2017_05_00 1 3 tone
2017_05_00 1 3 toy


In [17]:

# gb = df.groupby(['stimulusType']).get_group('rat')

stimGrouped = df.groupby('stimulusType')
ratGrpd = stimGrouped.get_group('rat')

print(ratGrpd)

print('reached end of file')

               date  animalNum  sessionNum  trialNum stimulusType  neuronID  \
36240    2017_05_00          1           1         3          rat         1   
36241    2017_05_00          1           1         3          rat         1   
36242    2017_05_00          1           1         3          rat         1   
36243    2017_05_00          1           1         3          rat         1   
36244    2017_05_00          1           1         3          rat         1   
36245    2017_05_00          1           1         3          rat         1   
36246    2017_05_00          1           1         3          rat         1   
36247    2017_05_00          1           1         3          rat         1   
36248    2017_05_00          1           1         3          rat         1   
36249    2017_05_00          1           1         3          rat         1   
36250    2017_05_00          1           1         3          rat         1   
36251    2017_05_00          1           1         3

In [ ]:
gb = df.groupby('stimulusType')

df_means = gb.apply(np.mean)
df_means

In [ ]:
for stimType in gb

In [141]:
ratData = df.loc[df['stimulusType'] == 'rat',:]
ussData = df.loc[df['stimulusType'] == 'USS',:]

KeyError: 'stimulusType'

In [142]:
print(len(ratData))
print(len(ussData))

NameError: name 'ratData' is not defined

In [27]:
print(ussData)

# slicing
df_big_force = df.loc[df['impact force (mN)'] > 1000, :]

df = pd.concat((df_low, df_high), axis=1)

# Specify indices we want (note parentheses holding each Boolean)
inds = (df['food density'] == 'high') & (df['cross-sectional area (sq micron)'] > 2000)

# Pull out areas
df.loc[inds, 'cross-sectional area (sq micron)']

df.corr()

# Rename the impact force column
df = df.rename(columns={'impact force (mN)': 'impf'})



# Write out DataFrame
df.to_csv('xa_combined.csv', index=False)

               date  animalNum  sessionNum  trialNum stimulusType  neuronID  \
90432    2017_05_00          1           1         5          USS         1   
90433    2017_05_00          1           1         5          USS         1   
90434    2017_05_00          1           1         5          USS         1   
90435    2017_05_00          1           1         5          USS         1   
90436    2017_05_00          1           1         5          USS         1   
90437    2017_05_00          1           1         5          USS         1   
90438    2017_05_00          1           1         5          USS         1   
90439    2017_05_00          1           1         5          USS         1   
90440    2017_05_00          1           1         5          USS         1   
90441    2017_05_00          1           1         5          USS         1   
90442    2017_05_00          1           1         5          USS         1   
90443    2017_05_00          1           1         5

In [16]:




inds = df.loc(df.animalNum == 1)
df[inds]

KeyError: <pandas.core.indexing._LocIndexer object at 0x7fedd38aadd8>